name: Secure CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  secure-build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code (aucun token d’écriture)
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 2. Setup JDK (Java 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # 3. Run tests
      - name: Run tests with Maven
        run: mvn test

      # 4. Scan dependencies with Snyk
      - name: Scan with Snyk
        uses: snyk/actions/maven@master
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # 5. Static code analysis with SonarQube
      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # 6. Build Docker image
      - name: Build Docker image
        run: docker build -t myapp-secure .

      # 7. Scan Docker image with Trivy
      - name: Trivy Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp-secure
          format: 'table'
          severity: 'CRITICAL,HIGH'

      # 6b. Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag myapp-secure ${{ secrets.DOCKER_USERNAME }}/myapp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

  secure-deploy:
    needs: secure-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # 8. Verify checksum (optional)
      - name: Verify checksum
        run: sha256sum -c checksum.txt

      # 9. Deploy via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
            docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:latest
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --restart=always --name myapp -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/myapp:latest
